apiVersion: v1
kind: Secret
metadata:
  name: mongodb-charts-admin
type: Opaque
stringData:
  findName: admin
  lastName: charts
  email: admin@example.com
  password: password
---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: mms-user-1
spec:
  username: CN=mms-user,OU=mms-project,O=mms-org
  project: my-project
  db: "$external"
  roles:
    - db: admin
      name: backup
    - db: admin
      name: restore
---
kind:  Role 
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-tools-operator
rules:
  - apiGroups: [zalando.org]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]
---
apiVersion: mongodb.com/v1alpha1
kind: MongoDBCharts
metadata:
  name: mongodb-charts
spec:
  useradmin: mongodb-charts-admin
  version: "19.09"
  





