---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mongodbcharts.mongodb.com
spec:
  group: mongodb.com
  version: v1alpha1
  scope: Namespaced
  names:
    kind: MongoDBCharts
    plural: mongodbcharts
    shortNames:
    - mdbchart
    singular: mongodbchart
  additionalPrinterColumns:
    - name: Version
      type: string
      description: The version of MongoDBCharts.
      JSONPath: .spec.version
    - name: UserAdmin
      type: string
      description: The name of a Secret containing the first UserAdmin account for MongoDBCharts.
      JSONPath: .spec.useradmin
    - name: Age
      type: date
      description: The time since the MongoDBCharts resource was created.
      JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            useradmin:
              type: string
            version:
              type: string
          required:
            - version
            - useradmin

