apiVersion: v1
kind: Secret
metadata:
  name: mongodb-charts-{{ .Release.Name }}-metadb-secret
  namespace: {{ .Release.Namespace }}
  labels:
    mongodbTool: mongodb-charts-{{ .Release.Name }}
type: Opaque
stringData:
    mongodb-uri: "mongodb://mongodb-charts-mongodb-charts-metadb-0.mongodb-charts-mongodb-charts-metadb-svc.chartstest.svc.cluster.local/?"
    xmongodb-uri: "mongodb+srv://mongodb-charts-{{ .Release.Name }}-metadb-svc/?ssl=false" 
